version: 4
useFMTitle: true
useNoteTitleForLink: true
mermaid: true
useKatex: true
dev:
  enablePreviewV2: true
site:
  siteUrl: "https://www.invak.id"
  copyAssets: true
  siteHierarchies:
    - home
    - blog
  siteRootDir: docs
  usePrettyRefs: true
  title: invak.id
  description: invakid404's personal website
  siteLastModified: false
  gh_edit_branch: main
  duplicateNoteBehavior:
    action: useVault
    payload:
      - blog
      - notes
      - kachvame-wiki
commands:
  lookup:
    note:
      selectionMode: extract
      confirmVaultOnCreate: false
      leaveTrace: false
      bubbleUpCreateNew: true
      fuzzThreshold: 0.2
  randomNote: {}
  insertNote:
    initialValue: templates
  insertNoteLink:
    aliasMode: none
    enableMultiSelect: false
  insertNoteIndex:
    enableMarker: false
workspace:
  workspaces:
    kachvame-wiki:
      remote:
        type: git
        url: "https://github.com/kachvame/wiki.git"
  vaults:
    - fsPath: ../inva-blog
      remote:
        type: git
        url: "https://github.com/invakid404/inva-blog.git"
      name: blog
    - fsPath: ../notes
      visibility: private
      remote:
        type: git
        url: "https://github.com/invakid404/notes.git"
      name: notes
    - fsPath: vault
      visibility: private
      workspace: kachvame-wiki
      name: kachvame-wiki
  journal:
    dailyDomain: daily
    name: journal
    dateFormat: y.MM.dd
    addBehavior: childOfDomain
  scratch:
    name: scratch
    dateFormat: y.MM.dd.HHmmss
    addBehavior: asOwnDomain
  task:
    name: ""
    dateFormat: ""
    addBehavior: childOfCurrent
    statusSymbols:
      "": " "
      wip: w
      done: x
      assigned: a
      moved: m
      blocked: b
      delegated: l
      dropped: d
      pending: "y"
    prioritySymbols:
      H: high
      M: medium
      L: low
    todoIntegration: false
    createTaskSelectionType: selection2link
  graph:
    zoomSpeed: 1
  enableAutoCreateOnDefinition: false
  enableXVaultWikiLink: false
  enableRemoteVaultInit: true
  enableUserTags: true
  enableHashTags: true
  workspaceVaultSyncMode: noCommit
  enableAutoFoldFrontmatter: false
  enableEditorDecorations: true
  maxPreviewsCached: 10
  maxNoteLength: 204800
preview:
  enableFMTitle: true
  enableNoteTitleForLink: true
  enableMermaid: true
  enablePrettyRefs: true
  enableKatex: true
  automaticallyShowPreview: false
