name: Publish

on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Restore Node modules cache
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: |
          node_modules
          .next/node_modules
        key: node-modules-${{ hashFiles('yarn.lock')}}

    - name: Install npm dependencies
      run: yarn

    - name: Remove private vaults
      run: |
        sudo apt update
        sudo apt install jq python3 python3-pip
        sudo pip3 install yq
        yq -yi '.workspace.vaults |= [.[] | select(.visibility != "private")]' dendron.yml
        yq -yi '[.workspace.vaults[].name] as $vaults | .site.duplicateNoteBehavior.payload |= [.[] | select(IN($vaults[]))]' dendron.yml

    - name: Initialize workspace
      run: yarn dendron workspace init

    - name: Initialize or pull nextjs template
      run: "(test -d .next) && (echo 'updating dendron next...' && cd .next && git reset --hard && git clean -f && git pull && yarn && cd ..) || (echo 'init dendron next' && npx dendron publish init)"

    - name: Delete next cache
      run: "(test -d .next/.next) && (rm -rf .next/.next && echo 'delete Next.js cache') || echo 'no Next.js cache found'"

    - name: Export notes
      run: npx dendron publish export --target github --yes

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: docs/
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
